language: android
android:
  components:
    - tools
    - android-23
    - build-tools-23.0.3
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.+
before_install:
 - chmod +x gradlew
after_failure:
 - cat file:///home/travis/build/Meravici/Wally/app/build/outputs/lint-results.html
 
