package com.wally.wally.config;

public interface TangoManagerConstants {
    String LOCALIZED = "UX_LOCALIZED";
    String LEARNING_AREA = "UX_LEANING_AREA_MSG";
    String NEW_ROOM_LEARNED = "UX_NEW_ROOM_LEARNED_MSG";

    String LOCALIZING_IN_NEW_AREA = "UX_LOCALIZING_IN_NEW_AREA_MSG";
    String LOCALIZING_IN_KNOWN_AREA = "UX_LOCALIZING_IN_KNOWN_AREA";

    String LOCALIZATION_LOST = "UX_LOCALIZATION_LOST";
    String LOCALIZATION_LOST_IN_LEARNING = "UX_LOCALIZATION_LOST_IN_LEARNING";
    String LOCALIZATION_TIMEOUT = "LOCALIZATION_TIMEOUT";
}